#!/bin/sh
# -----------------------------------------------------------------------------
# docker-teamspeak /start.sh script
#
# Authors: Isaac Bythewood, Simon Eisenmann
# Updated: Jan 2nd, 2017
# -----------------------------------------------------------------------------

set -ex

# Checking if files exist to make sure we're backing up the database to data
if [ ! -f /opt/teamspeak/ts3server.sqlitedb ] && [ -f /data/ts3server.sqlitedb ]
then
    ln -s /data/ts3server.sqlitedb /opt/teamspeak/ts3server.sqlitedb
fi

if [ -f /opt/teamspeak/ts3server.sqlitedb ] && [ ! -f /data/ts3server.sqlitedb ]
then
    mv /opt/teamspeak/ts3server.sqlitedb /data/ts3server.sqlitedb
    ln -s /data/ts3server.sqlitedb /opt/teamspeak/ts3server.sqlitedb
fi

if [ -f /opt/teamspeak/ts3server.sqlitedb ] && [ -f /data/ts3server.sqlitedb ]
then
    rm /opt/teamspeak/ts3server.sqlitedb
    ln -s /data/ts3server.sqlitedb /opt/teamspeak/ts3server.sqlitedb
fi

if [ ! -f /opt/teamspeak/serverkey.dat ] && [ -f /data/license/serverkey.dat ]
then
    ln -s /data/license/serverkey.dat /opt/teamspeak/serverkey.dat
fi

if [ ! -f /opt/teamspeak/licensekey.dat ] && [ -f /data/license/licensekey.dat ]
then
    ln -s /data/license/licensekey.dat /opt/teamspeak/licensekey.dat
fi

USER_ID=${LOCAL_USER_ID:-9001}

echo "Starting with UID : $USER_ID"
addgroup -g $USER_ID teamspeak
adduser -u $USER_ID -G teamspeak -h /opt/teamspeak -D teamspeak
export HOME=/opt/teamspeak
chown teamspeak:teamspeak $HOME

# Run the teamspeak server
export LD_LIBRARY_PATH=/opt/teamspeak
cd /opt/teamspeak
exec su-exec teamspeak ./ts3server logpath=/data/logs/
